<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Peter Stoltze and Anne Vinkel Hansen" />


<title>Practical A</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>





<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Practical A</h1>
<h4 class="author">Peter Stoltze and Anne Vinkel Hansen</h4>
<h4 class="date">Statistical Programming with R</h4>

</div>


<hr />
<p>Today we are going to get acquainted with <code>R</code>. A convenient way to work with <code>R</code> is through <code>RStudio</code> which adds many features and convenient options to the plain <code>R</code> interface. Most of these features go beyond the scope of this course, but as you will develop your <code>R</code> skillset, you might run into the need for them and hence <code>RStudio</code> so it is worthwhile to get to know <code>RStudio</code> right from the beginning.</p>
<p>If you have no experience with <code>R</code>, you will learn the most from following this document step by step. If you have some experience with <code>R</code> already, I suggest you try solving the questions without looking at the answers/walkthrough. You can always refer to the solutions as needed.</p>
<p>If you have any questions or if you feel that some code should be elaborated, feel free to ask.</p>
<hr />
<div id="exercises" class="section level4">
<h4>Exercises</h4>
<p>We start with the very basics and will move towards more advanced operations in <code>R</code>. First we will get acquainted with the language and the environment we work in.</p>
<hr />
<ol style="list-style-type: decimal">
<li><strong>Open <code>RStudio</code></strong></li>
</ol>
<p>The following window will appear. You might be faced with a bit different layout, but don’t dispair. Close to everything can be configured to your likings, including the colour scheme!<br />
<img src="figuresPractical/fig1.png" alt="alt text" /></p>
<p>RStudio is divided in 3 panes, namely the console, the environment/history pane and the pane where we can access our files, plots, the help files, make packages and view our data objects. You can change the order of the panes to your liking through <code>RStudio</code>’s preferences. I did, that is why your pane layout might differ from the layout in the above screenshot.</p>
<p>If we open an <code>R</code>-script (i.e. a file that contains <code>R</code> code), a fourth pane opens.</p>
<hr />
<ol start="2" style="list-style-type: decimal">
<li><strong>Create a new <code>R</code>-script</strong></li>
</ol>
<p>In the top left you will find <img src="figuresPractical/fig2.png" alt="alt text" />. Click it and select <code>R</code>-script. (Real hackers of course quickly learn the shortcut, Ctrl+Shift+N)</p>
<p>A new pane opens, and we can start typing our code. It is preferable to work from an <code>R</code>-script instead of directly working in the console for at least the following reasons (there are many more).</p>
<ol style="list-style-type: lower-alpha">
<li>You will not lose code, since <code>RStudio</code> caches files even if they are not saved.</li>
<li>You log your own work. Code does not disappear over time, as you save the code in a separate file.</li>
<li>With access to your <code>R</code>-script and data, others are able to exactly reproduce your work. Reproducibility is becoming increasingly more important, and this is where <code>RStudio</code> really excells.</li>
<li>You become more organized in coding, as you focus on creating readable code. In the long run, this will result in you becoming a more efficient programmer. Remember: efficient code runs faster.</li>
</ol>
<hr />
<ol start="3" style="list-style-type: decimal">
<li><strong>Type the following in your new <code>R</code>-script</strong></li>
</ol>
<pre class="r"><code># Exercise 3
a &lt;- 100</code></pre>
<p>The <code>#</code> tells <code>R</code> that everything that follows in that specific line is not to be evaluated as code. Hence, you can use the <code>#</code> to create a comment in your <code>R</code>-scripts (or to temporarily leave out a line of code). I used <code>#</code> here to elaborate that the following line is the code from exercise 3 (of practical A).</p>
<p>The line <code>a &lt;- 100</code> assigns the value <code>100</code> to object <code>a</code>. When you run your code, it will be saved. The value 100 and the letter <code>a</code> are chosen to illustrate assigning in <code>R</code>. You might as well assign <code>123</code> to <code>banana</code> if you like. Really, anything goes.</p>
<hr />
<ol start="4" style="list-style-type: decimal">
<li><strong>Select both lines of code and run the code by pressing Ctrl+Enter or Ctrl+R</strong></li>
</ol>
<p>Your code is executed and now appears in the console. If you type <code>a</code> in the console, <code>R</code> will return the assigned value. Try it! <img src="figuresPractical/fig3.png" alt="alt text" /></p>
<p>The shortcut Ctrl+Enter is your friend: it runs the current selection, or, if nothing is selected, the current line. If Ctrl+Enter yields no result, you probably have selected the console pane. You can switch to the code pane by moving the mouse cursor and clicking on the desired line in the code pane, or through Ctrl+1. Alternatively, you can move to the console through Ctrl+2.</p>
<p>You have now succesfully entered and executed your first code snippet in <code>R</code> by using <code>RStudio</code>.</p>
<hr />
<ol start="5" style="list-style-type: decimal">
<li><strong>Save your code file as <code>Practical_A.R</code> in a folder named <code>Practicals</code></strong></li>
</ol>
<p>You can use the standard Ctrl+S or click on the icon <img src="figuresPractical/fig4.png" alt="alt text" /> in the code pane.</p>
<p>Your document is now saved. We saved it in a separate folder so that we are able to create a project out of our practicals.</p>
<hr />
<ol start="6" style="list-style-type: decimal">
<li><strong>Create a project by clicking on <img src="figuresPractical/fig5.png" alt="alt text" /> in the top-right corner of <code>RStudio</code></strong></li>
</ol>
<p>Select “New Project”, click “Existing Directory” and navigate to the folder where you have just saved your code. When all is done, click on “Create Project”</p>
<p>You will notice in the files pane that a file <code>Practicals.RProj</code> has been created</p>
<p><img src="figuresPractical/fig6.png" /></p>
<p>The possibility to organize your work in projects is one of the benefits of using <code>RStudio</code>. Within a project, everything is relative to the <code>.Rproj</code> file. This means that if you share the folder with someone else, this someone only has to open the <code>.Rproj</code> file to be able to access and run all code and documents involved with this project. Again, when considering reproducability of results, working in projects is a huge advantage.</p>
<hr />
<ol start="7" style="list-style-type: decimal">
<li><strong>Open the <code>R</code>-script <code>notebook.R</code></strong></li>
</ol>
<p>Download the file (possibly to the same <code>Practicals</code> directory you just created) and open it in <code>RStudio</code> using Ctrl+O(pen) and browse to the position where you saved the file .</p>
<hr />
<ol start="8" style="list-style-type: decimal">
<li><strong>Have a look at the code in the script (but don’t run it just yet!) and try to decipher what is going on.</strong></li>
</ol>
<p>If you do not understand what you are looking at, please ask for help.</p>
<ol start="9" style="list-style-type: decimal">
<li><strong>If not open anymore, open your script by clicking on <code>Practical_A.R</code> in the files pane. Run both lines of code again and inspect the contents of the global environment by typing and running <code>ls()</code></strong></li>
</ol>
<p>The following is returned by <code>R</code></p>
<pre class="r"><code>ls()</code></pre>
<pre><code>## [1] &quot;a&quot;</code></pre>
<p>There is one object in the environment, and it is called <code>a</code>. If you look at the environment pane, you can quickly see the corresponding information (i.e. there is no need to type <code>ls()</code>) and you can see that object <code>a</code> contains a value. You can even see which value.</p>
<p>A value is the most basic object in <code>R</code>. The next step up in objects is a vector, followed by a matrix, followed by an array. Eventually, each of these objects can be stored in a list. We will learn about vectors, matrices and arrays later today.</p>
<hr />
<ol start="10" style="list-style-type: decimal">
<li><strong>Make two vectors: one named <code>vec1</code> with values 1 through 6 and one named <code>vec2</code> with letters A through F. </strong></li>
</ol>
<pre class="r"><code>vec1 &lt;- c(1, 2, 3, 4, 5, 6)
vec2 &lt;- c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;, &quot;D&quot;, &quot;E&quot;, &quot;F&quot;)</code></pre>
<p>To create a vector we used <code>c()</code>, which stands for ‘concatenation’. It is just a series of numbers or letters.</p>
<hr />
<ol start="11" style="list-style-type: decimal">
<li><strong>Create two matrices, one from <code>vec1</code> and one from <code>vec2</code>. The dimensions for both matrices are 3 rows by 2 columns. </strong></li>
</ol>
<pre class="r"><code>mat1 &lt;- matrix(vec1, nrow = 3, ncol = 2)
mat2 &lt;- matrix(vec2, nrow = 3, ncol = 2)</code></pre>
<p>To create a matrix we used <code>matrix()</code>. For a matrix we need to specify the dimensions (in this case 3 rows and 2 columns) and the input (in this case <code>vec1</code> or <code>vec2</code>) needs to match these dimensions.</p>
<hr />
<ol start="12" style="list-style-type: decimal">
<li><strong>Inspect your vectors and matrices. Are all numerical?</strong></li>
</ol>
<pre class="r"><code>vec1</code></pre>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<pre class="r"><code>vec2</code></pre>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot; &quot;F&quot;</code></pre>
<pre class="r"><code>mat1</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<pre class="r"><code>mat2</code></pre>
<pre><code>##      [,1] [,2]
## [1,] &quot;A&quot;  &quot;D&quot; 
## [2,] &quot;B&quot;  &quot;E&quot; 
## [3,] &quot;C&quot;  &quot;F&quot;</code></pre>
<p><code>vec1</code> and <code>mat1</code> contain numbers and <code>vec2</code> and <code>mat2</code> contain characters.</p>
<hr />
<ol start="13" style="list-style-type: decimal">
<li><strong>Make a matrix from both <code>vec1</code> and <code>vec2</code> with 6 rows and 2 columns. Inspect this matrix.</strong></li>
</ol>
<pre class="r"><code>mat3 &lt;- matrix(c(vec1, vec2), 6, 2)
mat3</code></pre>
<pre><code>##      [,1] [,2]
## [1,] &quot;1&quot;  &quot;A&quot; 
## [2,] &quot;2&quot;  &quot;B&quot; 
## [3,] &quot;3&quot;  &quot;C&quot; 
## [4,] &quot;4&quot;  &quot;D&quot; 
## [5,] &quot;5&quot;  &quot;E&quot; 
## [6,] &quot;6&quot;  &quot;F&quot;</code></pre>
<p>or</p>
<pre class="r"><code>mat3b &lt;- cbind(vec1, vec2)
is.matrix(mat3b)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>mat3b</code></pre>
<pre><code>##      vec1 vec2
## [1,] &quot;1&quot;  &quot;A&quot; 
## [2,] &quot;2&quot;  &quot;B&quot; 
## [3,] &quot;3&quot;  &quot;C&quot; 
## [4,] &quot;4&quot;  &quot;D&quot; 
## [5,] &quot;5&quot;  &quot;E&quot; 
## [6,] &quot;6&quot;  &quot;F&quot;</code></pre>
<p>If one or more elements in the matrix represent characters, all other elements are also converted to characters. A matrix is just for either numeric or character elements. Notice that the second approach (the column bind approach from <code>mat3b</code>) returns a matrix where the column names are already set to the name of the bound objects.</p>
<p>To solve the problem of charactered numbers we can create a dataframe. A dataframe is essentially a matrix that allows for character elements. The use of a dataframe is often preferred over the use of a matrix in <code>R</code>, except for purposes where pure numerical calculations are done, such as in matrix algebra. However, most datasets do contain character information and a dataframe would normally be your preferred choice when working with your own collected datasets in R.</p>
<hr />
<ol start="14" style="list-style-type: decimal">
<li><strong>Make a dataframe called <code>dat3</code> where <code>vec1</code> and <code>vec2</code> are both columns. Name the columns <code>V1</code> and <code>V2</code>, respectively. Use function <code>data.frame()</code>.</strong></li>
</ol>
<pre class="r"><code>dat3 &lt;- data.frame(V1 = vec1, V2 = vec2)
dat3</code></pre>
<pre><code>##   V1 V2
## 1  1  A
## 2  2  B
## 3  3  C
## 4  4  D
## 5  5  E
## 6  6  F</code></pre>
<hr />
<ol start="15" style="list-style-type: decimal">
<li><strong>Again, make a dataframe called <code>dat3b</code> where <code>vec1</code> and <code>vec2</code> are both columns. Name the columns <code>V1</code> and <code>V2</code>, respectively. Use function <code>as.data.frame()</code> on the matrix obtained from <code>Question 4</code>. </strong></li>
</ol>
<p>This is a tricky situation. At face value, everything may seem to be in order. But, be aware that the code</p>
<pre class="r"><code>dat3b &lt;- as.data.frame(mat3)
dat3b</code></pre>
<pre><code>##   V1 V2
## 1  1  A
## 2  2  B
## 3  3  C
## 4  4  D
## 5  5  E
## 6  6  F</code></pre>
<p>does not work properly (at least not as intended) as the matrix nature of <code>mat3</code> turned everything into a character value and you have lost the numerical nature of <code>vec1</code>. It may appear to be working, but if we check if column 1 is numerical, it turns out not to be the case.</p>
<hr />
<ol start="16" style="list-style-type: decimal">
<li><strong>Check if the first column in the data frames from Question 4 and Question 5 are indeed numeric. If not, determine what they are. </strong></li>
</ol>
<pre class="r"><code>is.numeric(dat3[, 1])</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>is.numeric(dat3b[, 1])</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>The first column in matrix <code>dat3b</code> obtained from Question 5 is indeed not numeric. As a matter of fact, it is also not a character variable.</p>
<pre class="r"><code>is.character(dat3b[, 1])</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>Rather tricky; the function <code>as.data.frame()</code> has converted the first variable to a factor.</p>
<pre class="r"><code>is.factor(dat3b[, 1])</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>This is due to us not specifying the variable correctly in the matrix we used to create the dataframe. Factors are categorical variables that are depicted by numbers. Character vectors are converted to factors in data frames.</p>
<hr />
<ol start="17" style="list-style-type: decimal">
<li><strong>Select 1) the third row, 2) the second column and 3) the intersection of these two in the dataframe <code>dat3</code> that you have created in Question 4. </strong></li>
</ol>
<pre class="r"><code>dat3[3, ] #3rd row</code></pre>
<pre><code>##   V1 V2
## 3  3  C</code></pre>
<pre class="r"><code>dat3[, 2] #2nd column</code></pre>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot; &quot;F&quot;</code></pre>
<pre class="r"><code>dat3$V2   #also 2nd column</code></pre>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot; &quot;F&quot;</code></pre>
<pre class="r"><code>dat3[3,2] #intersection</code></pre>
<pre><code>## [1] &quot;C&quot;</code></pre>
<p>The <code>[3,2]</code> index is very useful in ‘R’. The first number (before the comma) represents the row and the second number (after the comma) represents the column. For a vector there are no two dimensions and only one dimension can be called. For example, <code>vec1[3]</code> would yield <code>3</code>. Try it.</p>
<p>Columns can also be called by the <code>$</code> sign, but only if a name has been assigned. With dataframes assigning names happens automatically.</p>
<p>Note that <code>R</code> automatically reports the values the character column can take. This means that the column is indeed a factor (a categorical variable - as it is supposed to be). A useful function to inspect the structure of a dataframe is <code>str()</code>. Try running it.</p>
<pre class="r"><code>str(dat3)</code></pre>
<pre><code>## &#39;data.frame&#39;:    6 obs. of  2 variables:
##  $ V1: num  1 2 3 4 5 6
##  $ V2: chr  &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; ...</code></pre>
<p>Inspecting the structure of your data is vital, as you probably have imported your data from some other source. If we, at a later stage, start analyzing our data without the correct measurement level, we may run into problems. One problem that often occurs is that categorical variables (factors in <code>R</code>) are not coded as such.</p>
<hr />
<ol start="18" style="list-style-type: decimal">
<li><strong>Open the workspace <code>boys.RData</code>. You need to download this file and put it in the project folder.</strong> Either run the below code</li>
</ol>
<pre class="r"><code>load(&quot;boys.RData&quot;)</code></pre>
<p>or double-click the <code>boys.RData</code> file on your machine (right-click and <code>open with RStudio</code> if it does not open by default in <code>RStudio</code>, but in <code>R</code>).</p>
<!-- You can also import it directly from the internet by running and loading the below code connection -->
<!-- ```{r} -->
<!-- con <- url("https://gerkovink.github.io/Statistical-Programming-with-R/Contents/Material/Part%20B%20-%20How%20is%20R%20organized/boys.RData") -->
<!-- load(con) -->
<!-- ``` -->
<p>The <code>boys</code> object will be added to your Global Environment. You can now use the <code>boys</code> data by running</p>
<pre class="r"><code>boys</code></pre>
<hr />
<ol start="19" style="list-style-type: decimal">
<li><strong>Most packages have datasets included. Since we have not learned to load packages yet, you are presented with such a data set in a workspace. Open the <code>boys</code> dataset (it is from package <code>mice</code>, by the way) by typing <code>boys</code> in the console, and subsequently by using the function <code>View()</code>. </strong></li>
</ol>
<p>The output is not displayed here as it is simply too large.</p>
<p>Using <code>View()</code> is preferred for inspecting datasets that are large. <code>View()</code> opens the dataset in a spreadsheet-like window (conform MS Excel, or SPSS). If you <code>View()</code> your own datasets, you can not edit the datasets’ contents.</p>
<hr />
<ol start="20" style="list-style-type: decimal">
<li><strong>Find out the dimensions of the <code>boys</code> data set and inspect the first and final 6 cases in the data set. </strong> To do it numerically, find out what the dimensions of the boys dataset are.</li>
</ol>
<pre class="r"><code>dim(boys)</code></pre>
<pre><code>## [1] 748   9</code></pre>
<p>There are 748 cases on 9 variables. To select the first and last six cases, use</p>
<pre class="r"><code>boys[1:6, ]</code></pre>
<pre><code>##      age  hgt   wgt   bmi   hc  gen  phb tv   reg
## 3  0.035 50.1 3.650 14.54 33.7 &lt;NA&gt; &lt;NA&gt; NA south
## 4  0.038 53.5 3.370 11.77 35.0 &lt;NA&gt; &lt;NA&gt; NA south
## 18 0.057 50.0 3.140 12.56 35.2 &lt;NA&gt; &lt;NA&gt; NA south
## 23 0.060 54.5 4.270 14.37 36.7 &lt;NA&gt; &lt;NA&gt; NA south
## 28 0.062 57.5 5.030 15.21 37.3 &lt;NA&gt; &lt;NA&gt; NA south
## 36 0.068 55.5 4.655 15.11 37.0 &lt;NA&gt; &lt;NA&gt; NA south</code></pre>
<pre class="r"><code>boys[743:748, ]</code></pre>
<pre><code>##         age   hgt  wgt   bmi   hc  gen  phb tv   reg
## 7410 20.372 188.7 59.8 16.79 55.2 &lt;NA&gt; &lt;NA&gt; NA  west
## 7418 20.429 181.1 67.2 20.48 56.6 &lt;NA&gt; &lt;NA&gt; NA north
## 7444 20.761 189.1 88.0 24.60   NA &lt;NA&gt; &lt;NA&gt; NA  west
## 7447 20.780 193.5 75.4 20.13   NA &lt;NA&gt; &lt;NA&gt; NA  west
## 7451 20.813 189.0 78.0 21.83 59.9 &lt;NA&gt; &lt;NA&gt; NA north
## 7475 21.177 181.8 76.5 23.14   NA &lt;NA&gt; &lt;NA&gt; NA  east</code></pre>
<p>or, more efficiently:</p>
<pre class="r"><code>head(boys)</code></pre>
<pre><code>##      age  hgt   wgt   bmi   hc  gen  phb tv   reg
## 3  0.035 50.1 3.650 14.54 33.7 &lt;NA&gt; &lt;NA&gt; NA south
## 4  0.038 53.5 3.370 11.77 35.0 &lt;NA&gt; &lt;NA&gt; NA south
## 18 0.057 50.0 3.140 12.56 35.2 &lt;NA&gt; &lt;NA&gt; NA south
## 23 0.060 54.5 4.270 14.37 36.7 &lt;NA&gt; &lt;NA&gt; NA south
## 28 0.062 57.5 5.030 15.21 37.3 &lt;NA&gt; &lt;NA&gt; NA south
## 36 0.068 55.5 4.655 15.11 37.0 &lt;NA&gt; &lt;NA&gt; NA south</code></pre>
<pre class="r"><code>tail(boys)</code></pre>
<pre><code>##         age   hgt  wgt   bmi   hc  gen  phb tv   reg
## 7410 20.372 188.7 59.8 16.79 55.2 &lt;NA&gt; &lt;NA&gt; NA  west
## 7418 20.429 181.1 67.2 20.48 56.6 &lt;NA&gt; &lt;NA&gt; NA north
## 7444 20.761 189.1 88.0 24.60   NA &lt;NA&gt; &lt;NA&gt; NA  west
## 7447 20.780 193.5 75.4 20.13   NA &lt;NA&gt; &lt;NA&gt; NA  west
## 7451 20.813 189.0 78.0 21.83 59.9 &lt;NA&gt; &lt;NA&gt; NA north
## 7475 21.177 181.8 76.5 23.14   NA &lt;NA&gt; &lt;NA&gt; NA  east</code></pre>
<p>The functions <code>head()</code> and <code>tail()</code> are very useful functions. For example, from looking at both functions we can observe that the data are very likely sorted based on <code>age</code>.</p>
<hr />
<ol start="21" style="list-style-type: decimal">
<li><strong>It seems that the <code>boys</code> data are sorted based on <code>age</code>. Verify this.</strong></li>
</ol>
<p>To verify if the data are indeed sorted, we can run the following command to test the complement of that statement. Remember that we can always search the help for functions: e.g. we could have searched here for <code>?sort</code> and we would quickly have ended up at function <code>is.unsorted()</code> as it tests whether an object is <strong>not sorted</strong>.</p>
<pre class="r"><code>is.unsorted(boys$age)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>which returns <code>FALSE</code>, indicating that boys’ age is indeed sorted (we asked if it was unsorted!). To directly test if it is sorted, we could have used</p>
<pre class="r"><code>!is.unsorted(boys$age)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>which tests if data data are not unsorted. In other words the values <code>TRUE</code> and <code>FALSE</code> under <code>is.unsorted()</code> turn into <code>FALSE</code> and <code>TRUE</code> under <code>!is.unsorted()</code>, respectively.</p>
<hr />
<ol start="22" style="list-style-type: decimal">
<li><strong>Inspect the <code>boys</code> dataset with <code>str()</code>. Use one or more functions to find distributional summary information (at least information about the minimum, the maximum, the mean and the median) for all of the variables. Give the standard deviation for <code>age</code> and <code>bmi</code>. </strong></li>
</ol>
<pre class="r"><code>str(boys)</code></pre>
<pre><code>## &#39;data.frame&#39;:    748 obs. of  9 variables:
##  $ age: num  0.035 0.038 0.057 0.06 0.062 0.068 0.068 0.071 0.071 0.073 ...
##  $ hgt: num  50.1 53.5 50 54.5 57.5 55.5 52.5 53 55.1 54.5 ...
##  $ wgt: num  3.65 3.37 3.14 4.27 5.03 ...
##  $ bmi: num  14.5 11.8 12.6 14.4 15.2 ...
##  $ hc : num  33.7 35 35.2 36.7 37.3 37 34.9 35.8 36.8 38 ...
##  $ gen: Ord.factor w/ 5 levels &quot;G1&quot;&lt;&quot;G2&quot;&lt;&quot;G3&quot;&lt;..: NA NA NA NA NA NA NA NA NA NA ...
##  $ phb: Ord.factor w/ 6 levels &quot;P1&quot;&lt;&quot;P2&quot;&lt;&quot;P3&quot;&lt;..: NA NA NA NA NA NA NA NA NA NA ...
##  $ tv : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ reg: Factor w/ 5 levels &quot;north&quot;,&quot;east&quot;,..: 4 4 4 4 4 4 4 3 3 2 ...</code></pre>
<pre class="r"><code>summary(boys) #summary info</code></pre>
<pre><code>##       age              hgt              wgt              bmi       
##  Min.   : 0.035   Min.   : 50.00   Min.   :  3.14   Min.   :11.77  
##  1st Qu.: 1.581   1st Qu.: 84.88   1st Qu.: 11.70   1st Qu.:15.90  
##  Median :10.505   Median :147.30   Median : 34.65   Median :17.45  
##  Mean   : 9.159   Mean   :132.15   Mean   : 37.15   Mean   :18.07  
##  3rd Qu.:15.267   3rd Qu.:175.22   3rd Qu.: 59.58   3rd Qu.:19.53  
##  Max.   :21.177   Max.   :198.00   Max.   :117.40   Max.   :31.74  
##                   NA&#39;s   :20       NA&#39;s   :4        NA&#39;s   :21     
##        hc          gen        phb            tv           reg     
##  Min.   :33.70   G1  : 56   P1  : 63   Min.   : 1.00   north: 81  
##  1st Qu.:48.12   G2  : 50   P2  : 40   1st Qu.: 4.00   east :161  
##  Median :53.00   G3  : 22   P3  : 19   Median :12.00   west :239  
##  Mean   :51.51   G4  : 42   P4  : 32   Mean   :11.89   south:191  
##  3rd Qu.:56.00   G5  : 75   P5  : 50   3rd Qu.:20.00   city : 73  
##  Max.   :65.00   NA&#39;s:503   P6  : 41   Max.   :25.00   NA&#39;s :  3  
##  NA&#39;s   :46                 NA&#39;s:503   NA&#39;s   :522</code></pre>
<pre class="r"><code>sd(boys$age) #standard deviation for age</code></pre>
<pre><code>## [1] 6.894052</code></pre>
<pre class="r"><code>sd(boys$bmi, na.rm = TRUE) #standard deviation for bmi</code></pre>
<pre><code>## [1] 3.053421</code></pre>
<p>Note that <code>bmi</code> contains 21 missing values, e.g. by looking at the summary information. Therefor we need to use <code>na.rm = T</code> to calculate the standard deviation on the observed cases only.</p>
<hr />
<ol start="23" style="list-style-type: decimal">
<li><strong>Select all boys that are 20 years or older. How many are there?</strong></li>
</ol>
<p>The logical operators (TRUE vs FALSE) are a very powerful tool in <code>R</code>. For example, we can just select the rows (respondents) in the data that are older than 20 by putting the logical operater within the row index of the dataset:</p>
<pre class="r"><code>boys2 &lt;- boys[boys$age &gt;= 20, ]
nrow(boys2)</code></pre>
<pre><code>## [1] 12</code></pre>
<p>or, alternatively,</p>
<pre class="r"><code>boys2.1 &lt;- subset(boys, age &gt;= 20)
nrow(boys2.1)</code></pre>
<pre><code>## [1] 12</code></pre>
<hr />
<ol start="24" style="list-style-type: decimal">
<li><strong>Select all boys that are older than 19, but younger than 19.5. How many are there?</strong></li>
</ol>
<pre class="r"><code>boys3 &lt;- boys[boys$age &gt; 19 &amp; boys$age &lt; 19.5, ]
nrow(boys3)</code></pre>
<pre><code>## [1] 18</code></pre>
<p>or, alternatively,</p>
<pre class="r"><code>boys3.2 &lt;- subset(boys, age &gt; 19 &amp; age &lt; 19.5)
nrow(boys3.2)</code></pre>
<pre><code>## [1] 18</code></pre>
<hr />
<ol start="25" style="list-style-type: decimal">
<li><strong>What is the mean age of boys younger than 15 years of age that do not live in region <code>north</code>?</strong></li>
</ol>
<pre class="r"><code>mean(boys$age[boys$age &lt; 15 &amp; boys$reg != &quot;north&quot; ], na.rm = TRUE)</code></pre>
<pre><code>## [1] 6.044461</code></pre>
<p>or, alternatively,</p>
<pre class="r"><code>mean(subset(boys, age &lt; 15 &amp; reg != &quot;north&quot;)$age, na.rm=TRUE)</code></pre>
<pre><code>## [1] 6.044461</code></pre>
<p>The mean age is 6.0444609 years</p>
<hr />
<p>Today we have learned to use <code>R</code> at its basics. This offers tremendous flexibility, but may also be inefficient when our aim is some complex analysis, data operation of data manipulation. Doing advanced operations in basic <code>R</code> may require lots and lots of code. Tomorrow we will start using packages that allow us to do complicated operations with just a few lines of code.</p>
<p>As you start using <code>R</code> in your own research, you will find yourself in need of packages that are not part of the default <code>R</code> installation. The beauty of <code>R</code> is that its functionality is community-driven. People can add packages to <code>CRAN</code> that other people can use and improve. Chances are that a function and/or package has been already developed for the analysis or operation you plan to carry out. If not, you are of course welcome to fill the gap by submitting your own package.</p>
<hr />
<p>End of <code>Practical A</code>.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
